export const metadata = {
  title: "Blog",
  description: "Blog - Generated by create next app",
};

import Title from "@/components/PagesComp/Title"
import Link from 'next/link'


export const POST = [
  {
    id: 1,
    title: "Post 1",
    slug: "post-1",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 2,
    title: "Post 2",
    slug: "post-2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 3,
    title: "Post 3",
    slug: "post-3",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
];

const Blog = () => {
  return (
          <div>
              <Title title='Blog'/>
              <main className="container mx-auto">
                <Link href='/perfil' className="py-2">Ir a perfil</Link>
                  <div className="grip gap-5">
                    {
                      POST.map((post) => (
                        <div key={post.id} className="shadow rounded-md p-5">
                          <h1 className="text-2xl font-bold">{post.title}</h1>
                          <Link href={`/blog/${post.slug}`} >Mas informacion</Link>
                        </div>
                      ))
                    }
                  </div>
              </main>
          </div>
  )
}

export default Blog